[package]
name = "mailiner-css"
publish = false
version = "0.1.0"
edition = "2021"

[features]

[build-dependencies]
dioxus-daisyui = { workspace = true }
dioxus-tailwindcss = { workspace = true }

[dependencies]
dioxus-tailwindcss = { workspace = true }