//! Library surface for unit tests (formatters, loaders, download, account config).
pub mod a11y;
pub mod account;
pub mod account_config;
pub mod account_store;
pub mod account_vault;
pub mod address_book;
pub mod autodiscover;
pub mod background_sync;
pub mod conversation;
pub mod download;
pub mod draft_store;
pub mod formatter;
pub mod headers;
#[cfg(target_arch = "wasm32")]
pub mod idb;
pub mod keywords;
pub mod layout;
pub mod local_data;
pub mod mail_cache;
pub mod mail_file;
pub mod mail_rules;
pub mod mailbox;
pub mod message;
pub mod message_list_filter;
pub mod message_loader;
pub mod notifications;
pub mod object_cache;
pub mod offline_cache;
pub mod outbox_store;
pub mod phishing;
pub mod pin;
pub mod print;
pub mod provider_preset;
pub mod recipient_suggest;
pub mod reconnect;
pub mod selection;
pub mod send;
pub mod shortcuts;
pub mod smtp_inflight;
pub mod snippet;
pub mod snooze;
pub mod source;
pub mod toast;
pub mod ui_prefs;
pub mod vacation;

// connection / core_loop are binary-only (Dioxus signals + WASM WebSocket).
