[application]
name = "mailiner-rs"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Mailiner"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
script = []

[web.resource.dev]
#script = []
